[package]
name = "qt_simple_crypt_egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
qt_simple_crypt = { path = "../qt_simple_crypt" }
